- name: Configure Servers as github Runners
  hosts: myrunners
  tasks:
    - name: copy ssh key for test purposes
      command: ssh-import-id-gh MichaelKora
    - name: Create a folder
      command: mkdir -p actions-runner
    - name: Download the latest runner package
      command: curl -o actions-runner/actions-runner-linux-x64-2.288.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.288.1/actions-runner-linux-x64-2.288.1.tar.gz
    - name: Validate the hash
      command: echo "325b89bdc1c67264ec6f4515afda4534f14a6477d9ba241da19c43f9bed2f5a6  actions-runner/actions-runner-linux-x64-2.288.1.tar.gz" | shasum -a 256 -c
    - name: Extract the installer
      command: tar xzf actions-runner/actions-runner-linux-x64-2.288.1.tar.gz -C actions-runner/

- name: Activate and test the first runner
  hosts: runner-1
  vars:
    token: "string-token"
  tasks:
#    - name: copy ssh key for test purposes
#      command: ssh-import-id-gh MichaelKora
#    - name: Create a folder
#      command: mkdir -p actions-runner
#    - name: Download the latest runner package
#      command: curl -o actions-runner/actions-runner-linux-x64-2.288.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.288.1/actions-runner-linux-x64-2.288.1.tar.gz
#    - name: Validate the hash
#      command: echo "325b89bdc1c67264ec6f4515afda4534f14a6477d9ba241da19c43f9bed2f5a6  actions-runner/actions-runner-linux-x64-2.288.1.tar.gz" | shasum -a 256 -c
#    - name: Extract the installer
#      command: tar xzf actions-runner/actions-runner-linux-x64-2.288.1.tar.gz -C actions-runner/

    - name: Configure and start the runner1
      shell: |
        cd actions-runner/
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels linuxx64,runner1 --name condabuilder1 --unattended --ephemeral

- name: Activate and test the  second runner
  hosts: runner-2
  vars:
    token: "string-token"
  tasks:
    - name: Configure and start the runner2
      shell: |
        cd ./actions-runner
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels osx64,runner2 --name condabuilder2 --unattended --ephemeral
  
- name: Activate and test the  the runner3
  hosts: runner-3
  vars:
    token: "string-token"
  tasks:
    - name: Configure and start the runner3
      shell: |
        cd ./actions-runner
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels osxarm64,runner3 --name condabuilder3 --unattended --ephemeral

  
- name: Activate and test the  the runner4
  hosts: runner-4
  vars:
    token: "string-token"
  vars:
    token: "string-token"
  tasks:
    - name: Configure and start the runner4
      shell: |
        cd ./actions-runner
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels win64,runner4 --name condabuilder4 --unattended --ephemeral

  
- name: Activate and test the  the runner5
  hosts: runner-5
  vars:
    token: "string-token"
  tasks:
    - name: Configure and start the runner5
      shell: |
        cd ./actions-runner
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels linuxaarch64,runner5 --name condabuilder5 --unattended --ephemeral

  
- name: Activate and test the  the runner6
  hosts: runner-6
  vars:
    token: "string-token"
  tasks:
    - name: Configure and start the runner6
      shell: |
        cd ./actions-runner
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels linuxppc64le,runner6 --name condabuilder6 --unattended --ephemeral

  
- name: Activate and test the  the runner7
  hosts: runner-7
  vars:
    token: "string-token"
  tasks:
    - name: Configure and start the runner7
      shell: |
        cd ./actions-runner
        ./config.sh --url https://github.com/MichaelKora/mirror_conda --token ATILRBT6V45UYRLREDMWZ6DCIMD44 --labels noarch,runner7 --name condabuilder7 --unattended --ephemeral


- name: Configure with svc.sh
  hosts: myrunners
  become: yes
  become_user: ubuntu
  tasks:
    - name: ./svc.sh install && ./svc.sh start
      shell: |
        cd ./actions-runner
        sudo ./svc.sh install
        sudo ./svc.sh start
