name: Dowload and Mirror packages from anaconda 
on: [ push ]
#on:
#    schedule:
#        - cron: '*/30 * * * *'
#permissions:
#  contents: read
#  contents: write
#  pull-requests: write
#  packages: read
#  packages: write


defaults:
  run:
    working-directory: ./

jobs:
  create_oras_push:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
            ref: master

      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name: log in into oci repo & run the python script
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          echo ${{ env.GITHUB_TOKEN }} | oras login https://ghcr.io -u ${{ env.GITHUB_USER }} --password-stdin
          #conda-oci mirror --channel conda-forge --subdirs linux-64 -s osx-64 --packages xtensor --user ${{ env.GITHUB_USER }}
          python ./conductor.py ${{ env.GITHUB_USER }}
        shell: bash -l {0}

      - run: echo "🍏 The current status is ${{ job.status }}."
