name: Dowload and Mirror packages from anaconda 
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./

jobs:
  build-linux64-pkgs:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name:  clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s linux-64 --packages xtensor --user ${{ env.GITHUB_USER }}

  build-osx64-pkgs:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name:  clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s osx-64 --packages xtensor --user ${{ env.GITHUB_USER }}

  build-osxarm64-pkgs:    
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name:  clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s osx-arm64 --packages xtensor --user ${{ env.GITHUB_USER }}

  build-win64-pkgs:    
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name:  clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s win-64 --packages xtensor --user ${{ env.GITHUB_USER }}

  build-linuxaarch64-pkgs:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name:  clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s linux-aarch64 --packages xtensor --user ${{ env.GITHUB_USER }}

  build-linuxppc64le-pkgs:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest
      - name: clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s linux-ppc64le --packages xtensor --user ${{ env.GITHUB_USER }}

  build-noarch-pkgs:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - name:  clone project and mirror
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/mamba-org/conda_oci_mirror@main
          conda-oci mirror --channel conda-forge -s noarch --user ${{ env.GITHUB_USER }}
  
